
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author BHARTI BHATIA
 */
public class login extends javax.swing.JFrame {

    /**
     * Creates new form login
     */
    public login() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        signinpage = new javax.swing.JPanel();
        logo = new javax.swing.JLabel();
        loginicon = new javax.swing.JLabel();
        uname = new javax.swing.JTextField();
        uicon = new javax.swing.JLabel();
        picon = new javax.swing.JLabel();
        signin = new javax.swing.JButton();
        password = new javax.swing.JPasswordField();
        adminpanel = new javax.swing.JButton();
        remember = new javax.swing.JCheckBox();
        fpass = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setForeground(new java.awt.Color(0, 0, 0));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        signinpage.setBackground(new java.awt.Color(236, 246, 253));
        signinpage.setPreferredSize(new java.awt.Dimension(1500, 700));

        logo.setIcon(new javax.swing.ImageIcon("C:\\Users\\BHARTI BHATIA\\Desktop\\login logo.jpg")); // NOI18N

        loginicon.setIcon(new javax.swing.ImageIcon("C:\\Users\\BHARTI BHATIA\\Desktop\\login icon.png")); // NOI18N

        uname.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        uname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                unameActionPerformed(evt);
            }
        });

        uicon.setIcon(new javax.swing.ImageIcon("C:\\Users\\BHARTI BHATIA\\Desktop\\icon2.png")); // NOI18N
        uicon.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        picon.setIcon(new javax.swing.ImageIcon("C:\\Users\\BHARTI BHATIA\\Desktop\\login key.jpg")); // NOI18N
        picon.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        signin.setBackground(new java.awt.Color(153, 153, 153));
        signin.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        signin.setText("SIGN IN");
        signin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                signinActionPerformed(evt);
            }
        });

        password.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        password.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passwordActionPerformed(evt);
            }
        });

        adminpanel.setBackground(new java.awt.Color(153, 153, 153));
        adminpanel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        adminpanel.setText("ADMIN PANEL");
        adminpanel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adminpanelActionPerformed(evt);
            }
        });

        remember.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        remember.setText("Remember You ");

        fpass.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        fpass.setText("Forgotten Password");

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setText("Show password");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setText("LOGIN ");

        javax.swing.GroupLayout signinpageLayout = new javax.swing.GroupLayout(signinpage);
        signinpage.setLayout(signinpageLayout);
        signinpageLayout.setHorizontalGroup(
            signinpageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(signinpageLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(logo)
                .addGap(550, 550, 550)
                .addComponent(loginicon)
                .addContainerGap(620, Short.MAX_VALUE))
            .addGroup(signinpageLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(signinpageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(picon)
                    .addComponent(uicon))
                .addGap(49, 49, 49)
                .addGroup(signinpageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(signinpageLayout.createSequentialGroup()
                        .addGroup(signinpageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(remember, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(signin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(80, 80, 80)
                        .addGroup(signinpageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(fpass)
                            .addComponent(adminpanel)))
                    .addComponent(uname)
                    .addComponent(password, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, signinpageLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(673, 673, 673))
        );
        signinpageLayout.setVerticalGroup(
            signinpageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(signinpageLayout.createSequentialGroup()
                .addGroup(signinpageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(signinpageLayout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(logo)
                        .addGap(208, 208, 208))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, signinpageLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(loginicon)
                        .addGap(31, 31, 31)
                        .addComponent(jLabel2)
                        .addGap(35, 35, 35)))
                .addGroup(signinpageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(signinpageLayout.createSequentialGroup()
                        .addComponent(uname, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(29, 29, 29)
                        .addComponent(password, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(signinpageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(signin)
                            .addComponent(adminpanel))
                        .addGap(31, 31, 31)
                        .addGroup(signinpageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(remember)
                            .addComponent(fpass, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(signinpageLayout.createSequentialGroup()
                        .addComponent(uicon)
                        .addGap(29, 29, 29)
                        .addComponent(picon)))
                .addContainerGap(141, Short.MAX_VALUE))
        );

        getContentPane().add(signinpage, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void signinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_signinActionPerformed

        String s = uname.getText();
        //String p = (String) password.getPassword();
        
        
        if((uname.getText().equals("admin")) && (password.getText().equals("admin123")))
        {
            JOptionPane.showMessageDialog(this, "LOGIN SUCCESSFUL");
            
        }
        else 
        {
            JOptionPane.showMessageDialog(this, "LOGIN DENIED");
        }       
    }//GEN-LAST:event_signinActionPerformed

    private void adminpanelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adminpanelActionPerformed
            newadmin admin = new newadmin();
            this.dispose();
            admin.setVisible(true);
       
       
       
    }//GEN-LAST:event_adminpanelActionPerformed

    private void unameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_unameActionPerformed
       // uname.getText().equals("admin");
    }//GEN-LAST:event_unameActionPerformed

    private void passwordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passwordActionPerformed
      //password.getPassword().equals("admin123");
    }//GEN-LAST:event_passwordActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton adminpanel;
    private javax.swing.JLabel fpass;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel loginicon;
    private javax.swing.JLabel logo;
    private javax.swing.JPasswordField password;
    private javax.swing.JLabel picon;
    private javax.swing.JCheckBox remember;
    private javax.swing.JButton signin;
    private javax.swing.JPanel signinpage;
    private javax.swing.JLabel uicon;
    private javax.swing.JTextField uname;
    // End of variables declaration//GEN-END:variables
}
